# Generated by Django 5.1.3 on 2024-11-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.folder')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=5)),
                ('size', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.folder')),
            ],
        ),
    ]
