# Generated by Django 5.1.3 on 2024-11-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_uploadmodel_upload_path_alter_uploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.folder'),
        ),
    ]
