# Generated by Django 5.1.4 on 2024-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_rename_folder_mediafile_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
