# Generated by Django 5.1.4 on 2024-12-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0009_alter_mediafile_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
