# Generated by Django 5.1.4 on 2024-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0010_delete_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
